produccion.modelo.OrdenProduccionView=produccion.repositorio.RepositorioOrdenProduccionViewAdHocJPA
scada.modelo.MaquinasAutomataAnfra=scada.repositorio.RepositorioMaquinasAutomataAnfraJPA
scada.modelo.MemoriaAutomataAnfra=scada.repositorio.RepositorioMemoriaAutomataAnfraJPA